import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * The rule this file exists for is the last one: `process.env` is readable in exactly three
 * places, and nowhere else.
 *
 * A convention in a README is a convention until someone new adds one `process.env.FOO ??
 * 'default'` in a service at 6pm. This makes it a build failure. The two exemptions are the
 * config module itself, which is the whole point, and the drizzle-kit config, which
 * drizzle-kit loads in its own process before any application module exists.
 *
 * Type-aware linting is deliberately not switched on. It roughly triples lint time, and the
 * rules that need type information overlap heavily with what `tsc --strict` already rejects
 * in this codebase. If a rule shows up that genuinely needs types, it can be enabled then,
 * with the cost paid for a reason.
 */

const processEnvMessage =
  'Read configuration from apps/api/src/config.ts instead. process.env is validated in exactly one place.';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      // Local tooling scratch directory. It can hold whole checkouts of this repo nested
      // inside it, and linting those lints every file twice - the second copy carrying a
      // second tsconfig root, which the parser refuses to choose between, so every file in
      // it fails to parse.
      '.claude/**',
      // Generated by drizzle-kit; not ours to lint.
      'apps/api/drizzle/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true },
      ],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['error', { allow: ['error', 'warn'] }],

      // `process.env.X`, `process['env'].X` and `const { env } = process` are all caught by
      // this one rule. The selector below adds the shape it does not cover: aliasing the
      // whole object out of reach of a property check.
      'no-restricted-properties': [
        'error',
        { object: 'process', property: 'env', message: processEnvMessage },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'VariableDeclarator[init.object.name="process"][init.property.name="env"]',
          message: processEnvMessage,
        },
      ],
    },
  },

  {
    files: ['apps/web/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },

  {
    files: ['apps/api/src/config.ts', 'apps/api/drizzle.config.ts'],
    rules: {
      'no-restricted-properties': 'off',
      'no-restricted-syntax': 'off',
    },
  },

  {
    // `tests/properties/runs.ts` reads `LEDGER_PROPERTY_RUNS`, so CI can raise how many cases a
    // property runs without a third place that knows how to read configuration. Scoped to that
    // one file by exact path, the same way the block above singles out `config.ts` and
    // `drizzle.config.ts` - `runs.ts`'s own doc comment is what says it is the only file in the
    // test tree meant to use this.
    files: ['apps/api/tests/properties/runs.ts'],
    rules: {
      'no-restricted-properties': 'off',
      'no-restricted-syntax': 'off',
    },
  },

  {
    // Migrations, container setup and the migration CLI all print progress; that is their
    // whole output. Tests may print diagnostics.
    files: ['**/*.test.ts', 'apps/api/tests/**', 'apps/api/src/db/migrate.ts'],
    rules: {
      'no-console': 'off',
    },
  },
);
